# Generated by Django 6.1.1 on 2026-09-19 00:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва шаблону')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='template_previews/', verbose_name="Прев'ю")),
                ('slug', models.SlugField(unique=True, verbose_name='Ідентифікатор')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Шаблон резюме',
                'verbose_name_plural': 'Шаблони резюме',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Текст')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубліковано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Оголошення',
                'verbose_name_plural': 'Оголошення та новини',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Назва резюме')),
                ('status', models.CharField(choices=[('draft', 'Чернетка'), ('ready', 'Готове')], default='draft', max_length=10, verbose_name='Статус')),
                ('full_name', models.CharField(blank=True, max_length=150, verbose_name='ПІБ')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Телефон')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Адреса')),
                ('summary', models.TextField(blank=True, verbose_name='Про себе')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='resume_photos/', verbose_name='Фото')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to=settings.AUTH_USER_MODEL, verbose_name='Власник')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resumes', to='main.resumetemplate', verbose_name='Шаблон')),
            ],
            options={
                'verbose_name': 'Резюме',
                'verbose_name_plural': 'Резюме',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=200, verbose_name='Навчальний заклад')),
                ('degree', models.CharField(blank=True, max_length=150, verbose_name='Ступінь / спеціальність')),
                ('start_date', models.DateField(verbose_name='Дата початку')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата закінчення')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='main.resume')),
            ],
            options={
                'verbose_name': 'Освіта',
                'verbose_name_plural': 'Освіта',
                'ordering': ['order', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва навички')),
                ('level', models.PositiveSmallIntegerField(choices=[(1, 'Початковий'), (2, 'Базовий'), (3, 'Впевнений'), (4, 'Просунутий'), (5, 'Експерт')], default=3, verbose_name='Рівень')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='main.resume')),
            ],
            options={
                'verbose_name': 'Навичка',
                'verbose_name_plural': 'Навички',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=150, verbose_name='Компанія')),
                ('position', models.CharField(max_length=150, verbose_name='Посада')),
                ('start_date', models.DateField(verbose_name='Дата початку')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата закінчення')),
                ('is_current', models.BooleanField(default=False, verbose_name='Працюю зараз')),
                ('description', models.TextField(blank=True, verbose_name="Опис обов'язків")),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_experiences', to='main.resume')),
            ],
            options={
                'verbose_name': 'Досвід роботи',
                'verbose_name_plural': 'Досвід роботи',
                'ordering': ['order', '-start_date'],
            },
        ),
    ]
